List<String> regions = [
  //russia
  "Moscow",
  "Saint Petersburg",
  "Krasnodar Krai",
  "Novosibirsk",
  "Sverdlovsk",
  "Rostov",
  "Samara",
  "Nizhny Novgorod",
  "Chelyabinsk",
  "Bashkortostan",
  "Tatarstan",
  "Perm Krai",
  "Krasnoyarsk Krai",
  "Voronezh",
  "Volgograd",
  "Kemerovo",
  "Primorsky Krai",
  "Stavropol Krai",
  "Tyumen",
  "Irkutsk",
  "Kaliningrad",
  "Leningrad",
  "Omsk",
  "Belgorod",
  "Vladimir",
  "Kirov",
  "Kaluga",
  "Kursk",
  "Lipetsk",
  "Ryazan",
  "Saratov",
  "Ulyanovsk",
  "Yaroslavl",
  "Vologda",
  "Tula",
  "Novgorod",
  "Ivanovo",
  "Tver",
  "Penza",
  "Orenburg",
  "Kostroma",
  "Smolensk",
  "Tambov",
  "Astrakhan",
  "Bryansk",
  "Kurgan",
  "Altai Krai",
  "Oryol",
  "Kaluga",
  "Kamchatka Krai",
  "Khanty-Mansi Autonomous Okrug",
  "Komi",
  "Sakha",
  "Sakhalin",
  "North Ossetia-Alania",
  "Kabardino-Balkaria",
  "Karachay-Cherkess",
  "Chechen",
  "Adygea",
  "Ingushetia",
  "Dagestan",
  "Altai",
  "Tyva",
  "Buryatia",
  "Kalmykia",
  "Khakassia",
  "Chukotka Autonomous Okrug",
  "Magadan",
  "Kamchatka Krai",
  "Yamalo-Nenets Autonomous Okrug",
  "Sverdlovsk",
  "Khabarovsk Krai",
  "Jewish Autonomous Okrug",
  "Amur",
  "Pskov",
  "Chelyabinsk",
  "Yaroslavl",
  "Rostov",
  "Ryazan",
  "Samara",
  "Saratov",
  "Sverdlovsk",
  "Smolensk",
  "Tambov",
  "Tver",
  "Tomsk",
  "Tyumen",
  "Ulyanovsk",
  "Vladimir",
  "Volgograd",
  "Vologda",
  "Yaroslavl",
  "Jewish Autonomous Okrug",
  "Chukotka Autonomous Okrug",
  "Khanty-Mansi Autonomous Okrug",
  "Yamalo-Nenets Autonomous Okrug",
  "Nenets Autonomous Okrug",
  "Chechen",
  "Chuvashia",
  "Altai",
  "Buryatia",
  "Dagestan",
  "Ingushetia",
  "Kabardino-Balkaria",
  "Kalmykia",
  "Karachay-Cherkess",
  "Komi",
  "North Ossetia-Alania",
  "Adygea",
  "Tatarstan",
  "Khakassia",
  "Sakha",
  "Tyva",
  "Kola Peninsula",
  "Kamchatka Peninsula",
  "Russian Far East",
  "Siberia",
  "Ural Mountains",
  "Caucasus Mountains",
  "Central Siberian Plateau",
  "North Caucasus",
  "Black Sea Coast",
  "Volga River",
  "Yenisei River",
  "Amur River",
  "Lena River",
  "Ob River",
  "Kolyma River",
  "Dnieper River",
  "Kama River",
  "Don River",
  "Pechora River",
  "Khatanga River",
  "Yana River",
  "Northern European Plain",
  "West Siberian Plain"

      ///uzbekistan
      "Andijan",
  "Bukhara",
  "Fergana",
  "Jizzakh",
  "Karakalpakstan Republic",
  "Namangan",
  "Navoiy",
  "Qashqadaryo",
  "Samarkand",
  "Sirdaryo",
  "Surkhandarya",
  "Tashkent",
  "Tashkent City",
  "Xorazm"

      ///tadjikiston
      "Dushanbe"
      "Sughd",
  "Khatlon",
  "Gorno-Badakhshan Autonomous",
  "Districts of Republican Subordination",
  //kirgizya
  "Batken",
  "Chuy",
  "Issyk-Kul",
  "Jalal-Abad",
  "Naryn",
  "Osh",
  "Talas"

      ///kazakhstan
      "Aktobe",
  "Almaty",
  "Almaty",
  "Atyrau",
  "East Kazakhstan",
  "Karaganda",
  "Kostanay",
  "Kyzylorda",
  "Mangystau",
  "North Kazakhstan",
  "Nur-Sultan",
  "Pavlodar",
  "Turkestan",
  "West Kazakhstan",

  /// Afghanistan:
  "Badakhshan",
  "Badghis",
  "Baghlan",
  "Balkh",
  "Bamyan",
  "Daykundi",
  "Farah",
  "Faryab",
  "Ghazni",
  "Ghor",
  "Helmand",
  "Herat",
  "Jowzjan",
  "Kabul",
  "Kandahar",
  "Kapisa",
  "Khost",
  "Kunar",
  "Kunduz",
  "Laghman",
  "Logar",
  "Nangarhar",
  "Nimruz",
  "Nuristan",
  "Paktia",
  "Paktika",
  "Panjshir",
  "Parwan",
  "Samangan",
  "Sar-e Pol",
  "Takhar",
  "Uruzgan",
  "Wardak",
  "Zabul"

      ///iran
      "Alborz",
  "Ardabil",
  "Bushehr",
  "Chaharmahal and Bakhtiari",
  "East Azerbaijan",
  "Fars",
  "Gilan",
  "Golestan",
  "Hormozgan",
  "Ilam",
  "Isfahan",
  "Kerman",
  "Kermanshah",
  "Kohgiluyeh and Boyer-Ahmad",
  "Kurdistan",
  "Lorestan",
  "Markazi (Central)",
  "Mazandaran",
  "North Khorasan",
  "Qazvin",
  "Qom",
  "Razavi Khorasan",
  "Semnan",
  "Sistan and Baluchestan",
  "South Khorasan",
  "Tehran",
  "West Azerbaijan",
  "Yazd",
  "Zanjan"

      ///china
      "Anhui",
  "Beijing",
  "Chongqing",
  "Fujian",
  "Gansu",
  "Guangdong",
  "Guangxi",
  "Guizhou",
  "Hainan",
  "Hebei",
  "Heilongjiang",
  "Henan",
  "Hong Kong",
  "Hubei",
  "Hunan",
  "Inner Mongolia",
  "Jiangsu",
  "Jiangxi",
  "Jilin",
  "Liaoning",
  "Macau",
  "Ningxia",
  "Qinghai",
  "Shaanxi",
  "Shandong",
  "Shanghai",
  "Shanxi",
  "Sichuan",
  "Taiwan",
  "Tianjin",
  "Tibet",
  "Xinjiang",
  "Yunnan",
  "Zhejiang"

      ///japan
      "Hokkaido",
  "Tohoku",
  "Kanto",
  "Chubu",
  "Kansai",
  "Chugoku",
  "Shikoku",
  "Kyushu",
  "Okinawa",
  ///sauth korea
  "Seoul",
  "Busan",
  "Daegu",
  "Incheon",
  "Gwangju",
  "Daejeon",
  "Ulsan",
  "Sejong",
  "Gyeonggi",
  "Gangwon",
  "Chungcheongbuk",
  "Chungcheongnam",
  "Jeollabuk",
  "Jeollanam",
  "Gyeongsangbuk",
  "Gyeongsangnam",
  "Jeju",
  ///north korea
  "Pyongyang",
  "Chagang",
  "North Hamgyong",
  "South Hamgyong",
  "North Hwanghae",
  "South Hwanghae",
  "Kangwon",
  "North Pyongan",
  "South Pyongan",
  "Ryanggang",
  "Kaesong",
  /// United Arab Emirates
  "Abu Dhabi",
  "Ajman",
  "Dubai",
  "Fujairah",
  "Ras Al Khaimah",
  "Sharjah",
  "Umm Al Quwain"
];
